name: Update

on:
  schedule:
    - cron:  '*/30 * * * *'
  push:
    branches: [main]

jobs:
  cron: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update data
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: |
        npm install -g pnpm --no-frozen-lockfile
        pnpm recursive install --no-frozen-lockfile
        cd biketower
        npm run update
        cd ../chrudimka
        npm run update
      # commit changes
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated update   
        commit_author: Author <actions@github.com>
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 